### ISSUE TITLE
Aktualisierung des Editor-Fensters bei Wechsel der Grammatik (und des Parsers)

### ISSUE THREAD

**Issue by Grillenfaenger** [spinfo/syndred#7]
Eine neue Grammatik wird erst bei einer weiteren Eingabe auf das Editorfenster angewandt.
-Regex-zu-Regex (Grammatikänderung) funktioniert dann ganz gut.
-Regex zu EBNF-Parser gibt der Ebnf-Parser keine Rückmeldung mehr (Problem ist wohl der Parser selbst)
-EBNF-Parser zu Regex (nachdem der Ebnf-Parser keine Rückmeldung mehr gibt) funktioniert nicht mehr. So lange dieser aber läuft, funktioniert ein Wechsel zu Regex

**Comment by schlusslicht** [comment]
Changin/restarting the parser in the frontend now initially sends the editor content to the backend for parsing.
